projects:
  - projectPath: /library1
    artifactId: library1
    version: '0'
  - projectPath: /library2
    artifactId: library2
    version: '0'
  - projectPath: /library3
    artifactId: library3
    version: '0'
  - projectPath: /apt/mylibrary-api
    artifactId: apt-mylibrary-api
    version: '0'
  - projectPath: /apt/mylibrary-compile
    artifactId: apt-mylibrary-compile
    version: '0'
