projects:
  - projectPath: /library1
    artifactId: library1
    version: '2.1708264148299'
  - projectPath: /library2
    artifactId: library2
    version: '3.1708264158398'
  - projectPath: /library3
    artifactId: library3
    version: '4.1708264159854'
