projects:
  - projectPath: /library1
    artifactId: library1
    version: '3.1708756314269'
  - projectPath: /library2
    artifactId: library2
    version: '3.1708756312510'
  - projectPath: /library3
    artifactId: library3
    version: '3.1708756308813'
  - projectPath: /apt/mylibrary-api
    artifactId: apt-mylibrary-api
    version: '10.1708756300978'
  - projectPath: /apt/mylibrary-compile
    artifactId: apt-mylibrary-compile
    version: '3.1708756311139'
