projects:
  - projectPath: /library1
    artifactId: library1
    version: '3.1708272561580'
  - projectPath: /library2
    artifactId: library2
    version: '5.1708272614001'
  - projectPath: /library3
    artifactId: library3
    version: '5.1708272438582'
