common:
  groupId: com.ct.ct
projects:
  - projectPath: /library1
    artifactId: library1
    version: 1.0.0_DEBUG
  - projectPath: /library2
    artifactId: library2
    version: 1.0.0_DEBUG
  - projectPath: /library3
    artifactId: library3
    version: 1.0.0_DEBUG