projects:
  - projectPath: /library1
    artifactId: library1
    version: '4.1708756599481'
  - projectPath: /library2
    artifactId: library2
    version: '4.1708756597782'
  - projectPath: /library3
    artifactId: library3
    version: '4.1708756594183'
  - projectPath: /apt/mylibrary-api
    artifactId: apt-mylibrary-api
    version: '11.1708756585897'
  - projectPath: /apt/mylibrary-compile
    artifactId: apt-mylibrary-compile
    version: '4.1708756596473'
