projects:
  - projectPath: /library1
    artifactId: library1
    version: '0'
  - projectPath: /library2
    artifactId: library2
    version: '2.1708243855655'
  - projectPath: /library3
    artifactId: library3
    version: '2.1708243938931'
